owner = "alice"
teamchannel_collaborators_with_access = []
updated_at_timestamp = 1735136221
expires_at = 1737555421
node_name = "teamplace"
filepath_in_node = "/instant_message_browser"
text_message = "time"
links = []
