owner = "alice"
teamchannel_collaborators_with_access = []
updated_at_timestamp = 1735137081
expires_at = 1737556281
node_name = "teamplace"
filepath_in_node = "/instant_message_browser"
text_message = "home"
links = []
