owner = "alice"
teamchannel_collaborators_with_access = []
updated_at_timestamp = 1735588197
expires_at = 1738007397
node_name = "teamplace"
filepath_in_node = "/instant_message_browser"
text_message = "pickles"
links = []
