node_name = "tofu"
description_for_tui = "tofu"
node_unique_id = [8, 180, 152, 72]
directory_path = "project_graph_data/team_channels/tofu"
owner = "alice"
updated_at_timestamp = 1735690073
expires_at = 12846801184
teamchannel_collaborators_with_access = ["alice"]
agenda_process = "s"
goals_features_subfeatures_tools_targets = """
Features: s
Tools: s
Goals: s"""
scope = """
Project Type: s
MVP Goals: s"""
schedule_duration_start_end = [1732406400, 1732665600, 259200]

[[abstract_collaborator_port_assignments.alice_alice]]

[[abstract_collaborator_port_assignments.alice_alice.collaborator_ports]]
user_name = "alice"
ready_port = 46848
intray_port = 55903
gotit_port = 51783
