node_name = "teamtest"
description_for_tui = "teamtest"
node_unique_id = [160, 203, 4, 191]
directory_path = "project_graph_data/team_channels/teamtest"
owner = "initial_owner"
updated_at_timestamp = 1728307130
expires_at = 1728393530
teamchannel_collaborators_with_access = ["alice", "bob", "charlotte"]

# meeting rooms, collaborator_port_assignments
[abstract_collaborator_port_assignments.alice_bob]
collaborator_ports = [
    { user_name = "alice", ready_port = 50001, intray_port = 50002, gotit_port = 50003 },
    { user_name = "bob", ready_port = 50004, intray_port = 50005, gotit_port = 50006 },
]

[abstract_collaborator_port_assignments.alice_charlotte]
collaborator_ports = [
    { user_name = "alice", ready_port = 50007, intray_port = 50008, gotit_port = 50009 },
    { user_name = "charlotte", ready_port = 50010, intray_port = 50011, gotit_port = 50012 },
]

[abstract_collaborator_port_assignments.bob_charlotte]
collaborator_ports = [
    { user_name = "bob", ready_port = 50013, intray_port = 50014, gotit_port = 50015 },
    { user_name = "charlotte", ready_port = 50016, intray_port = 50017, gotit_port = 50018 },
]

agenda_process = "agenda blurb"
goals_features_subfeatures_tools_targets = "goals blurb"
scope = "scope blurb"
schedule_duration_start_end = [1724630400, 1724803200, 172800]
