node_name = "4_review"
description_for_tui = "review column"
node_unique_id = [95, 184, 17, 106]
directory_path = "project_graph_data/team_channels/teamtest/task_browser/4_review"
owner = "alice"
updated_at_timestamp = 1735689107
expires_at = 12846800218
teamchannel_collaborators_with_access = []
agenda_process = "e"
goals_features_subfeatures_tools_targets = """
Features: e
Tools: e
Goals: e"""
scope = """
Project Type: e
MVP Goals: e"""
schedule_duration_start_end = [1732406400, 1732665600, 259200]

[abstract_collaborator_port_assignments]
